# Water Conflicts in the Colorado River Basin
---
Week 2 - Discussion section

This discussion section will guide you through exploring data about water-related conflicts at the Colorado River Basin using data from the U.S. Geological Survey (USGS). In this discussion section, you will:

## General Directions
---
* Add comments in each one of your code cells.
* Include markdown cells in between your code cells to add titles and information.
* Indications about when to commit and push changes are included, but you are encouraged to commit and push more often.

## 1. Archive Exploration
---
a. Look through the dataset’s description in the ScienceBase repository. Find the following information:
* Where was the data collected from?
* During what time frame were the observations in the dataset collected?
* What was the author’s perceived value of this dataset?

b. In a markdown cell, use your answers to the previous questions to add a brief description of the dataset. Briefly discuss anything else that seems relevant to you. Include a citation, date of access, and a link to the archive.

c.Take a look at the data’s metadata by clicking on the “View” icon of the Coded Events Colorado River Basin Water Conflict Table Metadata.xml file.

**check git status -> stage changes -> check git status -> commit with message -> pull -> push changes**

In [8]:
import pandas as pd

crb_water = pd.read_csv('data/Colorado River Basin Water Conflict Table.csv')
crb_water.head()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,...,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,...,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,...,18,0,0,0,0,0,0,0,0,0

## 2. Data Loading
---

## 3. Preliminary data exploration
---

In [11]:
crb_water.count

<bound method DataFrame.count of      Event     Search Source                                   Newspaper  \
0        1     USGS1-50.docx               The Durango Herald (Colorado)
1        2     USGS1-50.docx  Journal, The (Cortez, Dolores, Mancos, CO)
2        3     USGS1-50.docx                       The Salt Lake Tribune
3        4     USGS1-50.docx                   Casa Grande Dispatch (AZ)
4        5     USGS1-50.docx                  The Aspen Times (Colorado)
..     ...               ...                                         ...
263    264  USGS301-350.docx               The Durango Herald (Colorado)
264    265  USGS301-350.docx  Rio Blanco Herald Times (Meeker, Colorado)
265    266  USGS301-350.docx                   Casa Grande Dispatch (AZ)
266    267  USGS301-350.docx                       The Salt Lake Tribune
267    268  USGS301-350.docx                   Casa Grande Dispatch (AZ)

                                         Article Title Duplicate Report Date  \
0    Tribes assert water rights on Colorado River B...     False    7-Apr-22
1    Native American tribes assert water rights on ...     False    7-Apr-22
2    'Very positive change.' New Utah law will be a...     False   17-Mar-22
3    Legislation would let an Arizona tribe lease C...     False   11-Dec-21
4    Historically excluded from Colorado River poli...     False   19-Dec-21
..                                                 ...       ...         ...
263  Water officials consider action for worst case...     False    9-Jun-09
264        Rangely hosts Colorado River District event     False   21-Apr-22
265  California water district lawsuit threatens dr...     False   18-Apr-19
266  Scientists want to flush water past Glen Canyo...     False   13-Dec-07
267         Arizona plan could devastate Pinal farmers       NaN    2-Feb-19

     Report Year Event Date  Event Day  Event Month  ...  \
0         2022.0        NaN        NaN          4.0  ...
1         2022.0        NaN        NaN          4.0  ...
2         2022.0        NaN        NaN          3.0  ...
3         2021.0        NaN        NaN         12.0  ...
4         2021.0        NaN        NaN         11.0  ...
..           ...        ...        ...          ...  ...
263       2019.0          6        NaN          6.0  ...
264       2022.0  4/13/2022       13.0          4.0  ...
265       2019.0          4        NaN          4.0  ...
266       2007.0         12        NaN         12.0  ...
267       2019.0  1/31/2019       31.0          1.0  ...

     Article Text Search - water rights  \
0                                    17
1                                    17
2                                    12
3                                     6
4                                    18
..                                  ...
263                                   3
264                                   3
265                                   2
266                                   0
267                                   2

    Article Text Search - intergovernmental  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
..                                      ...
263                                       0
264                                       0
265                                       0
266                                       0
267                                       0

    Article Text Search - water transfers Article Text Search - navigation  \
0                                       0                                0
1                                       0                                0
2                                       0                                0
3                                       0                                0
4                                       0                                0
..                                    ...                              ...
263                                     0                                0
264                                     0                                0
265                                     0                                0
266                                     0                                0
267                                     0                                0

    Article Text Search - fish Article Text Search - invasive  \
0                            0                              0
1                            0                              0
2                            1                              0
3                            0                              0
4                            0                              0
..                         ...                            ...
263                          0                              0
264                          0                              1
265                          0                              0
266                          0                              2
267                          0                              0

    Article Text Search - diversion Article Text Search - water diversion  \
0                                 0                                     0
1                                 0                                     0
2                                 0                                     0
3                                 0                                     0
4                                 0                                     0
..                              ...                                   ...
263                               0                                     0
264                               1                                     0
265                               0                                     0
266                               0                                     0
267                               0                                     0

     Article Text Search - instream Article Text Search - aquatic
0                                 0                             0
1                                 0                             0
2                                12                             1
3                                 0                             0
4                                 0                             0
..                              ...                           ...
263                               0                             0
264                               0                             0
265                               0                             0
266                               0                             0
267                               0                             0

[268 rows x 48 columns]>

In [12]:
crb_water.head()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,...,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,...,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,...,18,0,0,0,0,0,0,0,0,0

In [15]:
crb_water['Place'].info

<bound method Series.info of 0                                Durango, CO
1                                Durango, CO
2                            Great Salt Lake
3          Colorado River Indian Reservation
4            Southern Ute Indian Reservation
                       ...
263                        Western Slope, CO
264                        Western Slope, CO
265    State of Arizona, State of California
266                      Glen Canyon Dam, AZ
267                         State of Arizona
Name: Place, Length: 268, dtype: object>

## 4.Location column descriptions
---

In [19]:
crb_water['State'].value_counts()

State
AZ                            66
CO                            34
UT                            27
NV                            10
CA                             7
NM                             6
AZ; CA                         4
AZ; UT                         3
AZ; CA; CO; NV; NM; UT; WY     3
AZ; NV                         2
NV; AZ                         2
CO; AZ                         2
CO; UT; WY; NM                 2
AZ; NM                         1
CA; NV; AZ                     1
WY; UT; CO                     1
UT; CO; WY                     1
CO; WY                         1
AZ; CA; NV                     1
UT; AZ                         1
AZ; CO; NM; UT                 1
OH; UT                         1
TX                             1
Name: count, dtype: int64

In [18]:
crb_water['State'].unique()

array(['CO', 'UT', nan, 'AZ', 'OH; UT', 'AZ; CO; NM; UT', 'CA', 'AZ; UT',
       'AZ; NV', 'CO; UT; WY; NM', 'AZ; CA', 'UT; AZ', 'CO; WY', 'NV; AZ',
       'CO; AZ', 'AZ; CA; CO; NV; NM; UT; WY', 'AZ; CA; NV', 'NV', 'NM',
       'UT; CO; WY', 'CA; NV; AZ', 'AZ; NM', 'WY; UT; CO', 'TX'],
      dtype=object)

In [17]:
crb_water['Conflict Present'].value_counts

<bound method IndexOpsMixin.value_counts of 0      Y
1      Y
2      N
3      N
4      Y
      ..
263    N
264    N
265    Y
266    N
267    N
Name: Conflict Present, Length: 268, dtype: object>

In [14]:
crb_water.value_counts

<bound method DataFrame.value_counts of      Event     Search Source                                   Newspaper  \
0        1     USGS1-50.docx               The Durango Herald (Colorado)
1        2     USGS1-50.docx  Journal, The (Cortez, Dolores, Mancos, CO)
2        3     USGS1-50.docx                       The Salt Lake Tribune
3        4     USGS1-50.docx                   Casa Grande Dispatch (AZ)
4        5     USGS1-50.docx                  The Aspen Times (Colorado)
..     ...               ...                                         ...
263    264  USGS301-350.docx               The Durango Herald (Colorado)
264    265  USGS301-350.docx  Rio Blanco Herald Times (Meeker, Colorado)
265    266  USGS301-350.docx                   Casa Grande Dispatch (AZ)
266    267  USGS301-350.docx                       The Salt Lake Tribune
267    268  USGS301-350.docx                   Casa Grande Dispatch (AZ)

                                         Article Title Duplicate Report Date  \
0    Tribes assert water rights on Colorado River B...     False    7-Apr-22
1    Native American tribes assert water rights on ...     False    7-Apr-22
2    'Very positive change.' New Utah law will be a...     False   17-Mar-22
3    Legislation would let an Arizona tribe lease C...     False   11-Dec-21
4    Historically excluded from Colorado River poli...     False   19-Dec-21
..                                                 ...       ...         ...
263  Water officials consider action for worst case...     False    9-Jun-09
264        Rangely hosts Colorado River District event     False   21-Apr-22
265  California water district lawsuit threatens dr...     False   18-Apr-19
266  Scientists want to flush water past Glen Canyo...     False   13-Dec-07
267         Arizona plan could devastate Pinal farmers       NaN    2-Feb-19

     Report Year Event Date  Event Day  Event Month  ...  \
0         2022.0        NaN        NaN          4.0  ...
1         2022.0        NaN        NaN          4.0  ...
2         2022.0        NaN        NaN          3.0  ...
3         2021.0        NaN        NaN         12.0  ...
4         2021.0        NaN        NaN         11.0  ...
..           ...        ...        ...          ...  ...
263       2019.0          6        NaN          6.0  ...
264       2022.0  4/13/2022       13.0          4.0  ...
265       2019.0          4        NaN          4.0  ...
266       2007.0         12        NaN         12.0  ...
267       2019.0  1/31/2019       31.0          1.0  ...

     Article Text Search - water rights  \
0                                    17
1                                    17
2                                    12
3                                     6
4                                    18
..                                  ...
263                                   3
264                                   3
265                                   2
266                                   0
267                                   2

    Article Text Search - intergovernmental  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
..                                      ...
263                                       0
264                                       0
265                                       0
266                                       0
267                                       0

    Article Text Search - water transfers Article Text Search - navigation  \
0                                       0                                0
1                                       0                                0
2                                       0                                0
3                                       0                                0
4                                       0                                0
..                                    ...                              ...
263                                     0                                0
264                                     0                                0
265                                     0                                0
266                                     0                                0
267                                     0                                0

    Article Text Search - fish Article Text Search - invasive  \
0                            0                              0
1                            0                              0
2                            1                              0
3                            0                              0
4                            0                              0
..                         ...                            ...
263                          0                              0
264                          0                              1
265                          0                              0
266                          0                              2
267                          0                              0

    Article Text Search - diversion Article Text Search - water diversion  \
0                                 0                                     0
1                                 0                                     0
2                                 0                                     0
3                                 0                                     0
4                                 0                                     0
..                              ...                                   ...
263                               0                                     0
264                               1                                     0
265                               0                                     0
266                               0                                     0
267                               0                                     0

     Article Text Search - instream Article Text Search - aquatic
0                                 0                             0
1                                 0                             0
2                                12                             1
3                                 0                             0
4                                 0                             0
..                              ...                           ...
263                               0                             0
264                               0                             0
265                               0                             0
266                               0                             0
267                               0                             0

[268 rows x 48 columns]>

## 5. String accessor for pandas.Series
---

In [9]:
# CELL 1
import numpy as np
import pandas as pd 

# Example series
s = pd.Series(['California; Nevada', 'Arizona', np.nan, 'Nevada; Utah'])
s

0    California; Nevada
1               Arizona
2                   NaN
3          Nevada; Utah
dtype: object

In [20]:
# CELL 2
# str accessor (doesn't do anything by itself)
s.str

In [43]:
crb_water['State'].str

In [44]:
crb_water['State'].str.split(';')

0           [CO]
1           [CO]
2           [UT]
3            NaN
4            NaN
         ...
263         [CO]
264         [CO]
265    [AZ,  CA]
266         [AZ]
267         [AZ]
Name: State, Length: 268, dtype: object

In [45]:
crb_water['State'].str.split(';').explode()

0       CO
1       CO
2       UT
3      NaN
4      NaN
      ...
264     CO
265     AZ
265     CA
266     AZ
267     AZ
Name: State, Length: 320, dtype: object

In [21]:
# CELL 3
# Use str accessor with additional methods to perform string operations
s.str.split(';')

0    [California,  Nevada]
1                [Arizona]
2                      NaN
3          [Nevada,  Utah]
dtype: object

In [22]:
# CELL 4
s.str.split(';').explode()

0    California
0        Nevada
1       Arizona
2           NaN
3        Nevada
3          Utah
dtype: object

## 6. Examine state codes
---

In [46]:
#detects the  non-Na values
crb_water['State'].notna()

0       True
1       True
2       True
3      False
4      False
       ...
263     True
264     True
265     True
266     True
267     True
Name: State, Length: 268, dtype: bool

In [47]:
crb_water['State'].value_counts()

State
AZ                            66
CO                            34
UT                            27
NV                            10
CA                             7
NM                             6
AZ; CA                         4
AZ; UT                         3
AZ; CA; CO; NV; NM; UT; WY     3
AZ; NV                         2
NV; AZ                         2
CO; AZ                         2
CO; UT; WY; NM                 2
AZ; NM                         1
CA; NV; AZ                     1
WY; UT; CO                     1
UT; CO; WY                     1
CO; WY                         1
AZ; CA; NV                     1
UT; AZ                         1
AZ; CO; NM; UT                 1
OH; UT                         1
TX                             1
Name: count, dtype: int64

a challenge could be that

In [55]:
crb_water.loc[crb_water['State'].notna(), "State"]

0          CO
1          CO
2          UT
5          AZ
11     OH; UT
        ...
263        CO
264        CO
265    AZ; CA
266        AZ
267        AZ
Name: State, Length: 178, dtype: object

## 7. Brainstorm
---

## 8. Exploratory wrangling
---

In [50]:
#crb_water = crb_water.loc[crb_water['Conflict Present'] == 'Y', ['State', 'Conflict Present']]

Empty DataFrame
Columns: [State, Conflict Present]
Index: []

In [54]:
#step1:
crb_conflict = crb_water.loc[crb_water['Conflict Present'] == 'Y', 'State']
crb_conflict
#step 2
crb_split = crb_conflict.str.split(";")
crb_split
#step 3
crb_exploded = crb_split.explode()
crb_exploded
#step4: unique values, keeping the Nas
crb_unique = crb_exploded.unique()
crb_unique

array(['CO', nan, 'AZ', 'OH', ' UT', 'UT', 'CA', ' NV', ' WY', ' NM',
       ' CA', 'NV', ' AZ', ' CO', 'NM', 'WY'], dtype=object)

## 9. Find unique state codes
---

a.

In [ ]:
# states_unique = (
crb_water.loc[crb_water["Conflict Present"] == "Y", "State"]
    .str.split(';')

    
)

In [60]:
crb_strip = crb_exploded.str.strip()
crb_strip

0       CO
1       CO
4      NaN
5       AZ
7      NaN
      ...
258     UT
260    NaN
262     AZ
265     AZ
265     CA
Name: State, Length: 179, dtype: object

## 10. Visualize data exploration & discussion
---

In [64]:
import matplotlib.pyplot as plt
crb_strip.plot(kind='bar')

TypeError: no numeric data to plot