# **WEEK 3 Discussion section**

## **Set up**
---

1. Create a new Python notebook inside your eds220-discussion-sections directory and rename it to section-3-snowshoe-hares.ipynb. Workbench or local are ok.

2. Use the terminal to push this file to your remote repository.

## **General directions**
---

* Add comments as appropriate along your code.
* Include markdown cells in between your code cells to add titles and information to each exercise.
* Download the data file from the link in exercise 3. If you are working on workbench-1,
  * upload the file to the server.
  * Indications about when to commit and push changes are included
  *  Commit every time you finish a major step! Remember to write   your commits in the imperative mood.

In [2]:
# import libraries
import pandas as pd
import numpy as np

In [7]:
#download the data

hares = pd.read_csv("data/55_Hare_Data_2012.txt") 
hares.head() # 3380 rows and 14 cols

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population
3,11/26/1998,NaN,bonrip,2E,414D262D43,NaN,NaN,NaN,1490.0,135.0,NaN,931.0,51,Population
4,11/26/1998,NaN,bonrip,3B,414D2B4B58,NaN,NaN,NaN,1710.0,150.0,NaN,933.0,51,Population

In [8]:
hares

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population
3,11/26/1998,NaN,bonrip,2E,414D262D43,NaN,NaN,NaN,1490.0,135.0,NaN,931.0,51,Population
4,11/26/1998,NaN,bonrip,3B,414D2B4B58,NaN,NaN,NaN,1710.0,150.0,NaN,933.0,51,Population
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3375,8/8/2002,18:00:00,bonrip,1b,1201,1202,NaN,NaN,1400.0,NaN,NaN,63.0,64,Population
3376,8/8/2002,6:00:00,bonrip,4b,1201,1202,NaN,NaN,NaN,NaN,NaN,63.0,64,Population
3377,8/7/2002,NaN,bonrip,4b,1217,1218,NaN,NaN,1000.0,134.0,NaN,69.0,64,Population
3378,8/8/2002,NaN,bonrip,6d,1217,1218,NaN,NaN,990.0,NaN,NaN,69.0,64,Population
3379,8/6/2002,NaN,bonrip,4b,1058,1060,M,NaN,1460.0,119.0,NaN,32.0,64,Population

In [5]:
hares.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3380 entries, 0 to 3379
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        3380 non-null   object
 1   time        264 non-null    object
 2   grid        3380 non-null   object
 3   trap        3368 non-null   object
 4   l_ear       3332 non-null   object
 5   r_ear       3211 non-null   object
 6   sex         3028 non-null   object
 7   age         1269 non-null   object
 8   weight      2845 non-null   float64
 9   hindft      1633 non-null   float64
 10  notes       243 non-null    object
 11  b_key       3333 non-null   float64
 12  session_id  3380 non-null   int64
 13  study       3217 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 369.8+ KB

In [9]:
hares.describe() # seeing the mean , std, min

            weight       hindft        b_key   session_id
count  2845.000000  1633.000000  3333.000000  3380.000000
mean   1346.081547   130.872627   500.640864    53.232249
std     345.160112    16.155295   299.421121    33.171355
min       0.000000    60.000000     1.000000     1.000000
25%    1180.000000   128.000000   235.000000    22.000000
50%    1400.000000   135.000000   464.000000    55.000000
75%    1580.000000   140.000000   755.000000    82.000000
max    2365.000000   160.000000  1034.000000   113.000000

## 1. **Archive exploration**
---

A. Take some time to look through the dataset’s description in EDI and click around. Then click on View Full Metadata, go to the “Detailed Metadata” section and click on “Data Entities” to look at the descriptions for the dataset’s columns.

### B. 
- Who assembled this data, and why?
- What does a single row in the data represent?
- When and where were the observations collected?
- Does the dataset contain sensitive data?
- What study protocols were used to collect the data?
- What are the units for the hares’ weight?
- Does the metadata say how missing data is encoded?
- Is there a publication associated with this dataset?

### Who assembled this data and why?
 The Bonzana Creek LTER team

### What does a single row in the data represent?
one line is data from capture-recapture studies of snowshoe hares

### When and where were the observations collected?

- In the Alaskan Fairbanks AK

### When and where were the observations collected?
- The study was taken in 5 locales in the Tanana valley,from Tok in the east to Clear in the west from 1999 to 2002.

### Does the dataset contain sensitive data?
- Not that I can see

### What study protocols were used to collect the data?
- Capture and release

### What are the units for the hares’ weight?
- They use gtams for their weight

### Does the metadata say how missing data is encoded?
- No,it just says NaN

### Is there a publication associated with this dataset?
- No, its oncurring

### C. In your notebook: use a markdown cell to briefly answer these questions. Include as well a citation, date of access, and a link to the archive.
- It is considered a matter of professional ethics to acknowledge the work of other scientists. Thus, the Data User should properly cite the Data Set in any publications or in the metadata of any derived data products that were produced using the Data Set. Citation should take the following general form: Creator(s), Year of Data Publication, Title of Dataset, Publisher, Dataset identifier, Dataset URL, Dataset DOI. For Example: Van Cleve, Keith; Chapin, F. Stuart; Ruess, Roger W. 2016. Bonanza Creek Experimental Forest: Hourly Temperature (sample, min, max) at 50 cm and 150 cm from 1988 to Present, Bonanza Creek LTER - University of Alaska Fairbanks. BNZ:1, http://www.lter.uaf.edu/data/data-detail/id/1. doi:10.6073/pasta/725db90d86686be13e6d6b2da5d61217.
- Date of access: October 15, 2026
- [link to archive]'https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-bnz.55.22'

### D. Before you look at the data itself, think about what you learned about how this data was collected. In a markdown cell, write down two or three questions about possible issues you might find in the data.

- Has there been a sequence of change since the first time data was collected to the present day?
- If accuracy is an issue, how does the data stay consistent with constant updates?
- Does climate change play a key factor in the migration or population of these hares?

### 2. Adding an image
---
- Go to this link.

-Get the URL of the hare image. To do this:

- hover over the image –> right click –> “Copy Image Address”.
- At the end of the markdown cell with the dataset description, use markdown syntax to add the image from its URL:
  `![image description](URL-goes-here)`
- Do you need to add an attribution in the image description? Check the license at the bottom of the Wikimedia page.

  **commit, pull, push changes!!**

![SnowShoe Hare](https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/960px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail&_=20170313021652)

## 3. Data loading and preliminary exploration
---
1. Back in your notebook, import the `55_Hare_Data_2012.txt` file available here. Store it in a variable named `hares`.

2. Using pandas methods, obtain preliminary information and explore this data frame. Consider answering some of these questions:

- What are the dimensions of the data frame and what are the data types of the columns? Do the data types match what you would expect from each column?
- Are there any columns that have a significant number of NA values?
- What are the minimum and maximum values for the weight and hind feet measurements?
- What are the unique values for some of the categorical columns?
-Did any of the issues you anticipated in 1c show up?
CHECK IN WITH YOUR TEAM

**MAKE SURE YOU’VE ALL SUCCESSFULLY ACCESSED THE DATA BEFORE CONTINUING**

**commit, pull, and push changes**

In [19]:
# import 
import pandas as pd

hares = pd.read_csv("data/55_Hare_Data_2012.txt")

In [20]:
hares.head()

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population
3,11/26/1998,NaN,bonrip,2E,414D262D43,NaN,NaN,NaN,1490.0,135.0,NaN,931.0,51,Population
4,11/26/1998,NaN,bonrip,3B,414D2B4B58,NaN,NaN,NaN,1710.0,150.0,NaN,933.0,51,Population

In [21]:
hares.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3380 entries, 0 to 3379
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        3380 non-null   object
 1   time        264 non-null    object
 2   grid        3380 non-null   object
 3   trap        3368 non-null   object
 4   l_ear       3332 non-null   object
 5   r_ear       3211 non-null   object
 6   sex         3028 non-null   object
 7   age         1269 non-null   object
 8   weight      2845 non-null   float64
 9   hindft      1633 non-null   float64
 10  notes       243 non-null    object
 11  b_key       3333 non-null   float64
 12  session_id  3380 non-null   int64
 13  study       3217 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 369.8+ KB

In [22]:
hares.describe()

            weight       hindft        b_key   session_id
count  2845.000000  1633.000000  3333.000000  3380.000000
mean   1346.081547   130.872627   500.640864    53.232249
std     345.160112    16.155295   299.421121    33.171355
min       0.000000    60.000000     1.000000     1.000000
25%    1180.000000   128.000000   235.000000    22.000000
50%    1400.000000   135.000000   464.000000    55.000000
75%    1580.000000   140.000000   755.000000    82.000000
max    2365.000000   160.000000  1034.000000   113.000000

In [26]:
hares.dtypes

date           object
time           object
grid           object
trap           object
l_ear          object
r_ear          object
sex            object
age            object
weight        float64
hindft        float64
notes          object
b_key         float64
session_id      int64
study          object
dtype: object

In [41]:
hares.nunique

<bound method DataFrame.nunique of             date      time    grid trap       l_ear r_ear  sex  age  weight  \
0     11/26/1998       NaN  bonrip   1A  414D096A08   NaN  NaN  NaN  1370.0
1     11/26/1998       NaN  bonrip   2C  414D320671   NaN    M  NaN  1430.0
2     11/26/1998       NaN  bonrip   2D  414D103E3A   NaN    M  NaN  1430.0
3     11/26/1998       NaN  bonrip   2E  414D262D43   NaN  NaN  NaN  1490.0
4     11/26/1998       NaN  bonrip   3B  414D2B4B58   NaN  NaN  NaN  1710.0
...          ...       ...     ...  ...         ...   ...  ...  ...     ...
3375    8/8/2002  18:00:00  bonrip  1b         1201  1202  NaN  NaN  1400.0
3376    8/8/2002   6:00:00  bonrip  4b         1201  1202  NaN  NaN     NaN
3377    8/7/2002       NaN  bonrip   4b        1217  1218  NaN  NaN  1000.0
3378    8/8/2002       NaN  bonrip   6d        1217  1218  NaN  NaN   990.0
3379    8/6/2002       NaN  bonrip   4b        1058  1060    M  NaN  1460.0

      hindft notes  b_key  session_id       study
0      160.0   NaN  917.0          51  Population
1        NaN   NaN  936.0          51  Population
2        NaN   NaN  921.0          51  Population
3      135.0   NaN  931.0          51  Population
4      150.0   NaN  933.0          51  Population
...      ...   ...    ...         ...         ...
3375     NaN   NaN   63.0          64  Population
3376     NaN   NaN   63.0          64  Population
3377   134.0   NaN   69.0          64  Population
3378     NaN   NaN   69.0          64  Population
3379   119.0   NaN   32.0          64  Population

[3380 rows x 14 columns]>

* What are the dimensions of the data frame and what are the data types of the columns? Do the data types match what you would expect from each column?
  - grams & objects,float64

- Are there any columns that have a significant number of NA values?
  * rear,sex,age,notes, hindft
    
- What are the minimum and maximum values for the weight and hind feet measurements?
    * min: 0.000 and max: 2365.000000
- What are the unique values for some of the categorical columns?
    * there seems to be alot of numerical values within the categorical cols
-Did any of the issues you anticipated in 1c show up?
    * disorganization
      
**CHECK IN WITH YOUR TEAM**

## 4. Detecting messy values
---
1. In the metadata section of the EDI repository, find the allowed values for the hares’ sex. Create a small table in a markdown cell showing the values and their definitions.

2. Get the number of times each unique sex non-NA value appears.

3. Check the documentation of value_counts(). What is the purpose of the dropna parameter and what is its default value? Repeat step (b), this time adding the dropna=False parameter to value_counts().

4. Discuss with your team the output of the unique value counts. In particular:

5. Do the values in the sex column correspond to the values declared in the metadata?
6. What could have been potential causes for multiple codes?
7. Are there seemingly repeated values? If so, what could be the cause?
8. Write code to confirm your suspicions about d-iii.

**commit, pull, and push changes**

1. males (m), females(f) and male not confirmed (m?)
2.

Object `na` not found.

## 5. Brainstorm
---
- Individually, write step-by-step instructions on how you would wrangle the hares data frame to clean the values in the sex column to have only two classes female and male. Which codes would you assign to each new class? Remember: It’s ok if you don’t know how to code each step - it’s more important to have an idea of what you would like to do.

- Discuss your step-by-step instructions with your team.

- The next exercise asks you to clean the sex codes. There are many ways of doing this. Use the approach you came up with in your brainstorm, or try a different one!

## 6. 6. Clean values
---
- Create a new column called sex_simple where:
- F, f, and f_ (f with a space) in the sex column get assigned to ‘female’,
- M, m, and m_ (m with a space) get assigned to ‘male’, and
missing values stay NaN.

- You decide what to do with the other codes (?, F?, f?, M?, m?, pf). In a markdown cell, write your choice and why you made it.

- Check the counts of unique values (including NAs) in the new sex_simple column.
**commit, pull, and push changes**

## 7. 7. Calculate mean weight
---
Use groupby() to calculate the mean weight by sex using the new column. Compare your result with a team who handled the other codes differently. Did your choice change the result?

Write a full sentence explaining the results you obtained. Don’t forget to include units.

A news brief says: “Female snowshoe hares at Bonanza Creek are heavier than males.” With your team, list a few reasons why the data might not support this claim. Think about how the data was collected. Then pick one reason and write code to check it.

commit, pull, and push changes

### 8. Collect your code and explain your results
---
In a new code cell, collect all the relevant code to create a streamlined workflow to obtain the final result from exercise 7 starting from importing the data. Your code cell should:

Only print the final results for mean weight by sex_simple.
Not include output from intermediate variables or checks.
Not include methods or functions that do not directly contribute to the analysis (even if they don’t print anything ex: df.head()).
If appropriate, combine methods using method chaining instead of creating intermediate variables.
Comment your code following our class comments guidelines.
Use appropriate line breaks and indentation to make code readable.
commit, pull, and push changes